name: CI

on:
  push:
    branches:
      - "*"
    tags:
      - "*"
      - "!**-alpha**"

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 500

  luacheck:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Install and run Luacheck
        uses: nebularg/actions-luacheck@v1
        with:
          args: "--no-color -q"
          annotate: warning

  build:
    runs-on: ubuntu-latest
    needs:
      - setup
      - luacheck
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - name: Generate Changelog
        run: ./generate_changelog.sh

      - name: Update Build Date
        run: sed -i "s/@build-time@/`date +%Y%m%d%H%M%S`/" WeakAuras/Init.lua

      - name: Update Version
        run: sed -i "s/@project-version@/${{ github.ref }}/" WeakAuras/Init.lua

      - name: ZIP addon files
        run: zip -r Release.zip WeakAuras WeakAurasArchive WeakAurasModelPaths WeakAurasOptions WeakAurasTemplates

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          body_path: CHANGELOG.md
          draft: false
          prerelease: false

      - name: Upload ZIP to release
        id: upload-release-asset 
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps 
          asset_path: ./Release.zip
          asset_name: WeakAuras-MoP-${{ github.ref }}.zip
          asset_content_type: application/zip
